# Generated by Django 5.0.7 on 2024-10-24 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('home_team_goals', models.IntegerField(default=0)),
                ('away_team_goals', models.IntegerField(default=0)),
                ('is_overtime', models.BooleanField(default=False)),
                ('is_shootout', models.BooleanField(default=False)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='games.team')),
                ('away_team_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_game_data', to='games.teamdata')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='games.team')),
                ('home_team_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_game_data', to='games.teamdata')),
            ],
            options={
                'unique_together': {('home_team', 'away_team', 'game_date')},
            },
        ),
    ]
