# Generated by Django 5.1.2 on 2024-10-29 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_game_game_json_teamdata_team_data_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdata',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='goal_differential',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='goals_against',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='goals_for',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='l10_games_played',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='l10_losses',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='l10_wins',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='ot_losses',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='points',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='season',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='streak_code',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='streak_count',
        ),
        migrations.RemoveField(
            model_name='teamdata',
            name='wins',
        ),
    ]
