# Generated by Django 5.1.2 on 2025-06-20 23:39

import django.db.models.deletion
from django.db import migrations, models
import httpx

def assign_seasons_to_games(apps, schema_editor):
    Game = apps.get_model('games', 'Game')
    Season = apps.get_model('games', 'Season')

    # get a list of all NHL seasons and create an object for each one in the db
    seasons_url = f"https://api-web.nhle.com/v1/standings-season/"
    seasons_response = httpx.get(seasons_url)
    response_json = seasons_response.json()
    seasons = response_json.get("seasons")
    seasons_to_create = []

    for season in seasons:
        season_to_create = Season(id=season.get("id"),
                                  regularSeasonStart=season.get("standingsStart"),
                                  regularSeasonEnd=season.get("standingsEnd"),
                                  season_json=season)
        seasons_to_create.append(season_to_create)

    Season.objects.bulk_create(seasons_to_create)

    for season in Season.objects.all():
        season_id = season.id
        games = Game.objects.filter(game_json__season=season_id)
        games.update(season=season)

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.season'),
        ),
        migrations.RunPython(assign_seasons_to_games)
    ]
