# Generated by Django 5.2.3 on 2025-07-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_alter_teamdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='regularSeasonEnd',
            new_name='regular_season_end',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='regularSeasonStart',
            new_name='regular_season_start',
        ),
    ]
