# Generated by Django 5.2.3 on 2025-08-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_assign_season_to_preseason_playoff_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=3),
        ),
    ]
