services:
  database:
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./nhl-game-predictor-backend
    env_file:
      - ./nhl-game-predictor-backend/.env
    ports:
      - "8001:8000"
    depends_on:
      - database

volumes:
  postgres_data:
