services:
  database:
    container_name: nhl-game-predictor-db
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    container_name: nhl-game-predictor-backend
    build:
      context: ./nhl-game-predictor-backend
    env_file:
      - ./nhl-game-predictor-backend/.env
    ports:
      - "8001:8000"
    depends_on:
      - database

  frontend:
    container_name: nhl-game-predictor-frontend
    build:
      context: ./nhl-game-predictor-frontend
    env_file:
      - ./nhl-game-predictor-frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
