# Generated by Django 5.0.7 on 2024-10-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_capture_date', models.DateField()),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ot_losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('goal_differential', models.IntegerField()),
                ('l10_games_played', models.IntegerField()),
                ('l10_wins', models.IntegerField()),
                ('l10_losses', models.IntegerField()),
                ('streak_count', models.IntegerField()),
                ('streak_code', models.CharField(max_length=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_data', to='games.team')),
            ],
            options={
                'unique_together': {('team', 'data_capture_date')},
            },
        ),
    ]
