# Generated by Django 5.1.2 on 2024-10-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='city',
            new_name='name',
        ),
    ]
