# Generated by Django 5.1.2 on 2024-10-27 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_away_team_win_game_home_team_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_team_win',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team_win',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='winning_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to='games.team'),
        ),
    ]
