# Generated by Django 5.1.2 on 2024-10-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_game_away_team_win_remove_game_home_team_win_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='goal_differential',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='l10_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='l10_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='l10_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='ot_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
