# Generated by Django 5.1.2 on 2024-10-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_teamdata_games_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='streak_code',
            field=models.IntegerField(choices=[(0, 'Win'), (1, 'LOSS'), (2, 'Overtime')], default=1),
        ),
    ]
