# Generated by Django 5.1.2 on 2024-10-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_teamdata_streak_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='season',
            field=models.BigIntegerField(null=True),
        ),
    ]
