# Generated by Django 5.1.2 on 2024-10-28 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_season_teamdata_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchise_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='games.franchise'),
        ),
    ]
