# Generated by Django 5.1.2 on 2024-10-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_franchise_team_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='team_data_json',
            field=models.JSONField(default=dict),
        ),
    ]
