# Generated by Django 5.1.2 on 2024-10-29 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_remove_teamdata_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_team_goals',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team_goals',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_overtime',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_shootout',
        ),
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
    ]
