# Generated by Django 5.1.2 on 2024-10-29 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_remove_game_away_team_goals_remove_game_game_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_home_team_win', models.BooleanField(default=False)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('top_features', models.JSONField(blank=True, null=True)),
                ('game', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='games.game')),
            ],
        ),
    ]
