# Generated by Django 5.1.2 on 2024-10-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_gameprediction'),
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprediction',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictor.predictionmodel'),
        ),
        migrations.AlterField(
            model_name='gameprediction',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='games.game'),
        ),
        migrations.AlterUniqueTogether(
            name='gameprediction',
            unique_together={('game', 'model')},
        ),
    ]
