# Generated by Django 5.1.2 on 2024-11-04 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_gameprediction_model_alter_gameprediction_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_game_data', to='games.teamdata'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_game_data', to='games.teamdata'),
        ),
    ]
