# Generated by Django 5.2.3 on 2025-06-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_game_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
