# Generated by Django 5.2.3 on 2025-07-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_rename_regularseasonend_season_regular_season_end_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
    ]
