# Generated by Django 5.2.3 on 2025-07-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_assign_season_to_preseason_playoff_games'),
        ('predictor', '0002_alter_predictionmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='trained_seasons',
            field=models.ManyToManyField(related_name='prediction_models', to='games.season'),
        ),
    ]
