# Generated by Django 5.2.3 on 2025-07-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='predictionmodel',
            unique_together={('name', 'version')},
        ),
    ]
