# Generated by Django 5.2.3 on 2025-10-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_predictionmodel_trained_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='feature_importances',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
