name: Keep Server Active

on:
  schedule:
    - cron: "*/1 * * * *" # This cron expression means every minute

jobs:
  keep-server-active:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      - name: Run keep_server_active.py
        run: python ../../nhl-game-predictor-backend/keep_server_active.py
